name: Deploy

on:
  push:
  schedule:
    - cron: "0 8 * * 6" # 8AM Saturdays
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 1
      matrix:
        include:
          - environment: dev
            aws-access-key-id: DEV_AWS_ACCESS_KEY_ID
            aws-secret-access-key: DEV_AWS_SECRET_ACCESS_KEY
            should_run: true
          - environment: prod
            aws-access-key-id: PROD_AWS_ACCESS_KEY_ID
            aws-secret-access-key: PROD_AWS_SECRET_ACCESS_KEY
            should_run: ${{ github.ref == 'refs/heads/main' }}
    steps:
      - uses: actions/checkout@v2
        if: matrix.should_run
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[matrix.aws-access-key-id] }}
          aws-secret-access-key: ${{ secrets[matrix.aws-secret-access-key] }}
          aws-region: us-east-1
        if: matrix.should_run
      - name: Deploy to ${{ matrix.environment }}
        run: aws s3 sync --sse AES256 --delete src/ s3://neilfarrington-com-${{ matrix.environment }}-therailroad
        if: matrix.should_run
